### ISSUE TITLE
Support @this on function

### ISSUE THREAD

**Issue by Mogztter** [englercj/tsd-jsdoc#109]
I believe that the following code:
```js
/**
 * @this OtherThing
 */
function doStuff() {
}
```

should generate the following type definition:

```ts
declare function doStuff(this: OtherThing): void;
```

Currently it generates:

```ts
/**
 * @this OtherThing
 */
declare function doStuff(): void;
```

**Comment by englercj** [comment]
👍 Totally. I think that setting the type of `this` didn't exist in Typescript (or even jsdoc) at the time I originally wrote this.
