### ISSUE TITLE
Built-In Non-Primitive Types

### ISSUE THREAD

**Issue by englercj** [englercj/tsd-jsdoc#16]
There are many built-in non-primitive types (like Promise<T>, HTMLElement, Date, etc). Need a way to support these in the correct way where it works for all the different js environments, but also continues to warn on type resolution errors.

How can I know when a type is not in jsdoc, but will exist in the environment? Maybe I can use TypeScript global defs?

**Comment by bennyn** [comment]
@englercj I've read that you don't support the `Uint8Array` type (https://github.com/englercj/tsd-jsdoc/issues/19)? What's the problem with it? I've seen that some projects (like [protobuf.js](https://github.com/dcodeIO/protobuf.js)) can do it.

[**message.js**](https://github.com/dcodeIO/protobuf.js/blob/6.6.5/src/message.js#L62)

```js
/**
 * Decodes a message of this type.
 * @name Message.decode
 * @function
 * @param {Reader|Uint8Array} reader Reader or buffer to decode
 * @returns {Message} Decoded message
 */
Message.decode = function decode(reader) {
  return this.$type.decode(reader);
};
```

[**index.d.ts**](https://github.com/dcodeIO/protobuf.js/blob/6.6.5/index.d.ts)

```ts
export class Message {
  /**
   * Decodes a message of this type.
   * @name Message.decode
   * @function
   * @param {Reader|Uint8Array} reader Reader or buffer to decode
   * @returns {Message} Decoded message
   */
  public static decode(reader: (Reader|Uint8Array)): Message;
}
```

@dcodeIO: I've seen that you use **tsd-jsdoc** in your [protobuf.js](https://github.com/dcodeIO/protobuf.js) project. What did you do in order to make it work with an `Uint8Array`?

**Comment by dcodeIO** [comment]
protobuf.js currently uses a fork of this library (this was done do get this going asap), located here: https://github.com/dcodeIO/protobuf.js/tree/master/lib/tsd-jsdoc

Plan is to switch back to the new version of tsd-jsdoc eventually, after contributing the changes I've made.

**Comment by englercj** [comment]
@bennyn The old version of this lib wrote out types even when it didn't understand them. This was because the previous version didn't understand types at all, it operated on text. The new version operates on types and resolves them. This fixes a host of issues the first version had, and introduces a host of new features.

The catch becomes, how do I resolve a type (like `Uint8Array`) that isn't specified anywhere in your jsdoc. The answer is: have a whitelist of types that we treat specially. But where do I get that list? Haven't figured that part out yet, and therefore haven't fixed this yet.

If anyone has any suggestions I'm all ears.

**Comment by dcodeIO** [comment]
Closure compiler's externs could be a resource for gathering type information. These exist for all kinds of stuff, including common libraries and node.

**Comment by bennyn** [comment]
TypeScript also defines a number of default ECMAScript types here: https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es2015.d.ts

As a workaround, which "older" version of **tsd-jsdoc** do I need to install in order to get an output for the `Uint8Array`?

**Comment by dcodeIO** [comment]
@bennyn : protobuf.js's fork is based on [1.0.1](https://github.com/englercj/tsd-jsdoc/releases/tag/v1.0.1). Alternatively, if protobuf.js is present, you could also set `template: "node_modules/protobufjs/lib/tsd-jsdoc"` in your [jsdoc.conf](https://github.com/dcodeIO/protobuf.js/blob/master/config/jsdoc-types.json) for the time being.

**Comment by englercj** [comment]
The goal I want to achieve is to warn the user when I encounter an unknown type (something they should fix) but still allow built-in types to be output as-is.

I'll probably end up adding in some configuration on which typescript defs to use, defaulting to something largely encompassing.

**Comment by stereobooster** [comment]
Alternative way is to check if it is present in TypeScript definitions, like "@types/node": "^8.0.46",.

Because tsc (starting from 2.3) can be used to validate types based on jsdoc it will require those definitions too.

**Comment by englercj** [comment]
A basic version of this is working in the latest, using an MDN scrape.
