### ISSUE TITLE
Export module

### ISSUE THREAD

**Issue by ffflorian** [englercj/tsd-jsdoc#20]
// cc @dcodeIO

What JSDoc comment do I have to use to export a module? I have this sample code:

```js
/** @module MyModule */

/**
 * @param {string} message
 * @class MyClass
 */
class MyClass {
  constructor(message) {
    this.message = message;
  }
}

module.exports = MyClass;
```

And with the help of [dcodeIO/tsd-jsdoc](https://github.com/dcodeIO/tsd-jsdoc) I can generate the following `.d.ts` file:
```ts
/** @module MyModule */
module MyModule {
   /**
    * @param {string} message
    * @class MyClass
    */
   class MyClass {
       /**
        * @param {string} message
        * @class MyClass
        */
       constructor(message: string);

   }

}
```

But how can I generate `export module MyModule`? I read the JSDoc reference but could not figure it out. I'd be happy if you could help me with that 🙂

**Comment by englercj** [comment]
dcodeIO's fork is no the latest version. declare should be correctly added to all items output in the definition in the latest version.

You can try it out with `npm install tsd-jsdoc`. Right now the latest is `v2.0.0-beta.2`. If you have issues with that version, let me know.

**Comment by ffflorian** [comment]
@englercj Thanks for your reply.

Unfortunately I can't use your latest version in my project, because non-primitive types are not supported yet (https://github.com/englercj/tsd-jsdoc/issues/16). But I think it's more of a general TypeScript issue on my side - seems like I have to switch from `module.exports = MyClass` to `export MyClass`.

**Comment by englercj** [comment]
Right now it falls back to `any`, I'm hoping to have time next weekend to fix it up.

```ts
/**
 * @module MyModule
 */
declare namespace MyModule {
    /**
     * @param {Uint8Array} array
     * @class MyClass
     */
    class MyClass {
        constructor(array: any);

    }

}
```

**Comment by ffflorian** [comment]
Alright, thank you! 🙂
