### ISSUE TITLE
Properties missing when adding a module/namespace

### ISSUE THREAD

**Issue by ffflorian** [englercj/tsd-jsdoc#21]
Using the current beta, I have this example code:
```js
'use strict';

/** @module util */

/**
 * @class MyClass
 * @param {string} message
 * @returns {MyClass}
 */
class MyClass {
    constructor(message) {
        /** @type {string} */
        this.message = message;
    }
}
```

Which is converted to
```ts
/**
 * @module util
 */
declare namespace util {
    /**
     * @class MyClass
     * @param {string} message
     * @returns {MyClass}
     */
    class MyClass {
        constructor(message: string);

    }

}
```

As you can see, the `message` property is missing.

When I use the following code (without `module`), `this.message` is not missing:
```js
'use strict';

/**
 * @class MyClass
 * @param {string} message
 * @returns {MyClass}
 */
class MyClass {
    constructor(message) {
        /** @type {string} */
        this.message = message;
    }
}
```

Converted:
```ts
/**
 * @class MyClass
 * @param {string} message
 * @returns {MyClass}
 */
declare class MyClass {
    constructor(message: string);

    /**
     * @type {string}
     */
    message: string;

}
```

**Comment by englercj** [comment]
Interesting, thanks for the repro case I will look into this soon.

**Comment by englercj** [comment]
Looks like this is a jsdoc issue with parsing ES6 classes:

https://github.com/jsdoc3/jsdoc/issues/1182

The names are output incorrectly and therefore tsd-jsdoc can't resolve them.

**Comment by ffflorian** [comment]
@englercj Thanks for looking into this. We'll have to wait for a JSDoc fix then.

**Comment by bennyn** [comment]
@englercj The jsdoc3/jsdoc#1182 issue has been resolved with JSDoc 3.5.0: https://github.com/jsdoc3/jsdoc/issues/1182#issuecomment-313750674

Current release version of JSDoc is 3.5.4, so it looks like this issue here can get fixed? 🤗

**Comment by englercj** [comment]
Does it work now when using jsdoc v3.5?

**Comment by englercj** [comment]
Looks like this has been fixed.

**Comment by bennyn** [comment]
Sorry, I haven't tested with JSDoc 3.5.0. It has been a while. But Florian posted demo code [here](https://github.com/englercj/tsd-jsdoc/issues/21#issue-216142330) which could be used for a unit test in your library?
