### ISSUE TITLE
Invalid output on functions taking params argument

### ISSUE THREAD

**Issue by RMcNeely** [englercj/tsd-jsdoc#25]
We're using this template to generate a definition file for our library and we've come across something that doesn't seem to be accounted for. We frequently use the pattern of passing an object named `params` to different functions throughout the library. These functions take this design with their JSDoc comments:

```
/**
* A function that does something
* @param {object} params periodicity arguments
* @param {number} [params.var1]
* @param {string} [params.var2] 
* @param {string} [params.var3] 
* @memberof Library.SubNamespace
*/
function something(param){
    ...
}
```
It seems that this pattern isn't used in Typescript and the only way (in my understanding) to use it to define an interface for each param when its used. By default tsd-jsdoc outputs something like this:

```
something(params: any, params.var1?: number, params.var2?: string, params.var3?: string): void;
```

I'm sure that we're not the only people who utilize this design pattern and it would be nice to have this addition. I've taken a look thru the code and I'm not 100% sure whether this should be handled by this code or by dts-dom.

**Comment by englercj** [comment]
Thanks for the report, closing this to track under #23
