### ISSUE TITLE
Configuration option for "types.d.ts" location

### ISSUE THREAD

**Issue by bennyn** [englercj/tsd-jsdoc#26]
If I use `tsd-jsdoc` as a JSDoc template, then it will write the `types.d.ts` file into JSDoc's documentation directory. It would be nice if I could specify a separate location where I want the `types.d.ts` file to go.

My current setup is this (`package.json`):

```json
  "scripts": {
    "jsdoc": "jsdoc --template node_modules/tsd-jsdoc --readme ./README.md --destination ./doc src/uuid.js"
  }
```

At the moment `types.d.ts` will be inside of `doc/types.d.ts`.

**Comment by englercj** [comment]
Curently it does use the `destination` option to write the file:

https://github.com/englercj/tsd-jsdoc/blob/b2403a45c937951c92a311f401cb0af443be1ac9/src/publish.ts#L26-L38

**Comment by englercj** [comment]
Ping, can you clarify what you are asking for? When using this lib as the template only the `types.d.ts` file is output. If you want documentation output you will need to run a separate command with a different template.

**Comment by bennyn** [comment]
I wanted to specify the location where `types.d.ts` is written to. To me it looked liked that it will be always saved inside the location of the JSDoc output.

**Comment by englercj** [comment]
It will be saved to whereever you specify using `--destination`. In your OP you specify `--destination ./doc`.
