### ISSUE TITLE
Cannot read property 'kind' of null (2.0.0 beta 3)

### ISSUE THREAD

**Issue by DDtMM** [englercj/tsd-jsdoc#28]
I was trying to use this project to generate typings for an existing project.  If I just use jsdoc, it generates documentation correctly.  However, when using tsd-jsdoc I'm getting Cannot read property 'kind' of null in dts-dom.

At the bottom are the configurations I used and the command I run.  This should be enough after running `npm install` to reproduce the error.  My goal is to generate types for toneJs. 

## Update 1
There seemed to be two issues occurring.  The first error would occur because dts-dom was trying to write an undefined value, when I added a guard for that condition in dts-dom my original error went away.  After that dts-dom would get error that the kind of 'property' wasn't supported.  The generated typings looked mostly okay, but every so often there was a missing type or parameter name.  So obviously I fixed a symptom not the problem.

**packages.json**
```
{
  "name": "blah",
  "version": "1.0.0",
  "dependencies": {
    "dts-dom": "^0.1.18",
    "jsdoc":"~3.4.3",
    "tone": "^0.10.0",
    "tsd-jsdoc":"^2.0.0-beta.3",
    "@types/webaudioapi": "^0.0.27"
  }
}
```

**conf.json**
```
{
    "opts": {
        "template": "./node_modules/tsd-jsdoc",  
        "destination": "./outtsd/",          
        "recurse": true        
    }
}
```

**The command I'm executing**
`jsdoc ./node_modules/tone/Tone -r -c conf.json`

**Comment by macleodbroad-wf** [comment]
One of your issues may be related to https://github.com/englercj/tsd-jsdoc/issues/31

**Comment by englercj** [comment]
Most useful is a block of JS/JSDoc that when run through this template produces your error. Thanks!

**Comment by ndry** [comment]
Reproduces on 2.0.0-beta.6 on the following JS:

```
/**
 * @class A
 */
(function() {
    /**
     */
    A.x;
}());
```

**Comment by solominsn** [comment]
I encountered a similar problem in my code. The root cause of the problem is missing comment for A.x. JSDoc add "x" property and set type to null. I think in this case tsd-jsdoc should set type to "Any".

**Comment by englercj** [comment]
I'm currently working on a rewrite which should clean this up.

**Comment by englercj** [comment]
v2 was just released and this seems to be working as expected now.
