### ISSUE TITLE
Support of "nullable  types" or optional paramaters ({?number}, {string} [myParam], etc)

### ISSUE THREAD

**Issue by VinceOPS** [englercj/tsd-jsdoc#29]
Hi,

First things first: thanks for this lib. It works beautifully, even if still "experimental".

I started using it to get autocompletion from VSCode intellisense accross my pure javascript object services/controllers (AngularJS app). I recently implemented Flowtype in this same projet and noticed that I could simply use the generated `tsd` file as a **flow-typed** definition. Which is quite a good thing, as the flowtype parser/checker use it to operate type-checking accross all my documented code (it was not possible, by default, with pure javascript object services or controllers).

I'm having an issue, though, with nullable types, like:
```javascript
/**
 * @param {?number} eventValue Value attached to the target event (might be null).
 */
```
which are converted (in the tsd file) to
```javascript 
/**
 * @param {number} eventValue Value attached to the target event (might be null).
 */
```

Is there anything I missed about the proper way to use the lib? May I do a PR if I create a clean fix for this? 

Thanks

**Comment by englercj** [comment]
The jsdoc comment it output verbatim from what jsdoc gives us. If the comment is wrong in the output, then jsdoc isn't parsing it the way you think it is. I'm pretty sure that is CC syntax not JSDoc (strictly speaking), maybe that is the issue?

That being said, there isn't really a "nullable" concept in Typescript so I'm not sure how I would express that concept anyway (outside the comment).

**Comment by VinceOPS** [comment]
Hi @englercj 

Thanks for your quick answer.
You're right about nullable parameter for Typescript.

The syntax comes from [usejsdoc.org](http://usejsdoc.org/tags-type.html): 

> Nullable type | A number or null. 
> `{?number}`
> This indicates that the type is either the specified type, or null.

But you're right, what I'd rather use is **optional parameter**, which is like:
```javascript
/**
 * @param {number} [eventValue] (optional) Value attached to the target event.
 */
```

> Optional parameter | An optional parameter named foo.
> @param {number} [foo]
> Indicates that the parameter is optional. When using JSDoc's syntax for optional parameters, you can also indicate the value that will be used if a parameter is omitted.

Which should be, in typescript:
```typescript
function logEvent(eventValue?: number) { }
```
According to the [TS doc](https://www.typescriptlang.org/docs/handbook/functions.html) @ "Optional and Default Parameters"

**Comment by englercj** [comment]
This should work correctly now when marked as optional, is that working for you?

As for nullable, not sure why your comment is rewritten...

**Comment by NewFuture** [comment]
Hi @englercj, thanks for your great tools.

but, it's still not working for me (2.0.0-beta.3)

JavaScript
```js
/**
 * @interface i
 */
var i = {}
/**
 * @method i.f
 * @param {number} [optional] - optional pararms
 */
i.f = function (optional) { }
````
.d.ts
```ts
/**
 * @interface i
 */
declare interface i {
    /**
     * @method i.f
     * @param {number} [optional] - optional pararms
     */
    f(optional: number): void; // should be f(optional?: number)
}
```
When commentting `i` as `class`, it will parse correctly.
is there any bug?

**Comment by VinceOPS** [comment]
@englercj Sorry for the delay - nope, the "optional parameter" syntax is not working.
Just like @NewFuture , I am using `@interface` (appropriate).

**Comment by englercj** [comment]
Hmm, I'll have to look into that. If it is working in class, but not interface then it is likely a bug. Strangely though this lib doesn't treat functions in interfaces and classes differently. It is possible jsdoc has another parsing issue.

**Comment by NewFuture** [comment]
I built the js file to html by the JSDOC,.
in the result,  the `optional` will be marked as  `opt` correctly.

Maybe jsdoc has different behaviors for the methods of class and inteface.

**Comment by NewFuture** [comment]
@englercj 
i think it is a bug of dts-dom. 
https://github.com/RyanCavanaugh/dts-dom/blob/master/lib/index.ts#L672-L674

here it doesn't add `?` for the method of interface

**Comment by englercj** [comment]
Ah, great catch! That certainly seems like the issue. Thanks for tracking this down.

**Comment by VinceOPS** [comment]
Hi guys, thank you for catching this.
I guess I'll just create an issue for dts-dom and let you know when this is fixed.

**Comment by NewFuture** [comment]
sure, I create an issue in dts-dom https://github.com/RyanCavanaugh/dts-dom/issues/27

**Comment by VinceOPS** [comment]
(previous comment removed)

Thanks for handling this with us @NewFuture ! Thanks again for your work @englercj

**Comment by NewFuture** [comment]
fixed
