### ISSUE TITLE
Map @typedefs with properties to interfaces

### ISSUE THREAD

**Issue by jvilk** [englercj/tsd-jsdoc#3]
[@typedefs can have properties on them.](http://usejsdoc.org/tags-typedef.html) When that occurs, I think they should be mapped to interfaces.

**Comment by englercj** [comment]
I think this makes a lot of sense, I'll see if I can put together something soon.

**Comment by englercj** [comment]
Ha, just realized I did already implement this just had a bug. Fixing now.

**Comment by englercj** [comment]
Just released `v2.0.0-beta.1`, and I think this is active there.

**Comment by englercj** [comment]
Nope this works using Object Type notation in v2 rather than using interfaces.
