### ISSUE TITLE
how to [overload] function

### ISSUE THREAD

**Issue by NewFuture** [englercj/tsd-jsdoc#30]
Hi,  I have a problem to declare the overload function.

jscomments:
```js
/**
 * @function 
 * @name f
 * @return {number[]}
 */
/**
 * @function 
 * @name f
 * @param {string} key
 * @return {number}
 */
```
the result:
```ts
/**
 * @function
 * @name f
 * @return {number[]}
 */
declare function f(): number;
```
expect:
```ts
declare function f(): number[];
declare function f(key:string): number;
```

The JSDOC default template can build both functions
>f() → {Array.<number>}
>f(key) → {number}

it there any way to do like this?

**Comment by englercj** [comment]
Ah I think this is because I use the FQN of a function as the key for storing it; so currently there can only be one. Good catch.

**Comment by NewFuture** [comment]
hi, look here https://github.com/englercj/tsd-jsdoc/blob/master/src/Emitter.ts#L177-L179

I remove those 3 lines and using the `@variation ` it weill work correctly

```js
/**
 * @function 
 * @name f
 * @variation 1
 * @return {number[]}
 */
/**
 * @function 
 * @name f
 * @variation 2
 * @param {string} key
 * @return {number}
 */
```
it will  parse as `f(1)` and `f(2)`

But I'm not sure whether there is any side effects

**Comment by NewFuture** [comment]
hi, @englercj 
I think it should be filtered by the `longname` rather than the `name` , if filter is needed here.

please fix it, thanks~

**Comment by englercj** [comment]
So there are two issues here.

Firstly, JSDoc will not have 2 declarations for two symbols that have the same longname. In your example, both `f` functions have the same longname and are therefore combines. Simply adding `@variation <something>` fixes that.

Secondly, two functions that share the same name in a class or namespace will get deduped by tsd-jsdoc even if they have different longnames. The only way to truly support this is to check if their longnames are different or they take different params. This isn't as easy as it sounds, and I've started work on it, but it will take some time.

**Comment by tambien** [comment]
Thanks for the great library! Checking out this issue in jsdocs repo (jsdoc3/jsdoc#1017), it seems like there is a way to add multiple docs to a single statement by combining the end of one comment block with the beginning of the next. 

i was able to get tsd-jsdoc to correctly document an overloaded function by doing something like this: 

```
/**
 *  Test if the argument is a boolean.
 *  @variation 1
 *  @param {boolean} arg the argument to test
 *  @returns {true} true if the arg is a boolean
 *  @static
 *  @memberOf MyClass
 *//**
 *  Test if the argument is a boolean.
 *  @variation 2
 *  @param {*} arg the argument to test
 *  @returns {false} true if the arg is a boolean
 *  @static
 *  @memberOf MyClass
 */
```

Could this combined syntax alleviate the need to include the `@variation` tag?

**Comment by englercj** [comment]
In my experience, no the variation tag is required. It is up to jsdoc to give us the right info, and I've always had to use `@variation` in the past, despite what that ticket says.
