### ISSUE TITLE
Interfaces name is prefixed with 'I'

### ISSUE THREAD

**Issue by osechet** [englercj/tsd-jsdoc#4]
When running tsd-jsdoc on [openlayers 3](https://github.com/openlayers/ol3), it prefixes the interface names with 'I' which lead to errors since typescript cannot find the original type. For example, the `olx.style.CircleOptions` interface is created as:
```
interface ICircleOptions {
...
}
```
but others types still reference it as `CircleOptions`:
```
class Circle ... {
    constructor(opt_options?: olx.style.CircleOptions);
...
}
```

What is the reason for that 'I' prefix?

**Comment by englercj** [comment]
Probably isn't necessary, can you give a me a code snippet that reproduces?

**Comment by osechet** [comment]
It's rather difficult to provide a snippet that reproduces the behavior of jsdoc with openlayers. They use plugins to preprocess their files.
For example, the `CircleOptions` type is defined as follow:
```
/**
 * @typedef {{fill: (ol.style.Fill|undefined),
 *     radius: number,
 *     snapToPixel: (boolean|undefined),
 *     stroke: (ol.style.Stroke|undefined),
 *     atlasManager: (ol.style.AtlasManager|undefined)}}
 */
olx.style.CircleOptions;

/**
 * Fill style.
 * @type {ol.style.Fill|undefined}
 * @api
 */
olx.style.CircleOptions.prototype.fill;
...
```
and results as:
```
/**
 * @typedef {{fill: (ol.style.Fill|undefined),
 *     radius: number,
 *     snapToPixel: (boolean|undefined),
 *     stroke: (ol.style.Stroke|undefined),
 *     atlasManager: (ol.style.AtlasManager|undefined)}}
 */
interface ICircleOptions {
    fill: (ol.style.Fill|undefined);
    ...
}
```
Everything is fine except the 'I' prefix.

In your code, I saw you just add that prefix. Is it possible to have an option to enable/disable that behavior?

**Comment by englercj** [comment]
Thanks for opening #5, I'm sure that will be super useful!

**Comment by englercj** [comment]
Merged!
