### ISSUE TITLE
Why do we have to copy the members of interface to class definitions?

### ISSUE THREAD

**Issue by e-cloud** [englercj/tsd-jsdoc#42]
see https://github.com/englercj/tsd-jsdoc/blob/07c6298604494d0612cfcfd1f5bbb134ce0a0d26/src/Emitter.ts#L335

a reasonable version
```
// jsdoc marked as mixin
interface A {
	a(): void;
}

// jsdoc marked as interface
interface B {
	b(): void;
}

class C implements A, B {
}
```

current output
```
// jsdoc marked as mixin
interface A {
	a(): void;
}

// jsdoc marked as interface
interface B {
	b(): void;
}

class C implements A, B {
	static a(): void;
	b(): void;
}
```
The reason of static occurrence is because in jsdoc mixins do not apply `scope: instance`.

I can not figure out why should we copy those members to class. IMO, it's unnecessary.

**Comment by englercj** [comment]
Because the first thing you listed is invalid Typescript.

```

**Comment by e-cloud** [comment]
Emmmmm, @englercj you are right. We may achieve the same goal via simpler solution. See https://github.com/Microsoft/TypeScript/issues/340#issuecomment-184964440

**Comment by englercj** [comment]
Seems reasonable, happy to merge a PR that uses namespace merging instead of copying members.

**Comment by englercj** [comment]
v2 was just released and after the rewrite I used this namespace merging technique for classes that implement interfaces.
