### ISSUE TITLE
TypeError: o.members is not iterable

### ISSUE THREAD

**Issue by irgendwr** [englercj/tsd-jsdoc#44]
```
$ npm ls | grep jsdoc
+-- jsdoc@3.5.5
`-- tsd-jsdoc@2.0.0-beta.5
```

First up: its a bit annoying that you changed the required template path from `./node_modules/tsd-jsdoc` to `./node_modules/tsd-jsdoc/dist` after `2.0.0-beta.3` without mentioning it anywhere.

But my main issue is the following:
```
$ jsdoc -c config.json
sinusbot-scripting-docs\node_modules\tsd-jsdoc\dist\Emitter.js:183
                for (const member of o.members) {
                                       ^

TypeError: o.members is not iterable
    at Emitter._resolveObjects (sinusbot-scripting-docs\node_modules\tsd-jsdoc\dist\Emitter.js:183:40)
    at Emitter.parse (sinusbot-scripting-docs\node_modules\tsd-jsdoc\dist\Emitter.js:39:14)
    at new Emitter (sinusbot-scripting-docs\node_modules\tsd-jsdoc\dist\Emitter.js:30:14)
    at Object.publish (sinusbot-scripting-docs\node_modules\tsd-jsdoc\dist\publish.js:11:21)
    at Object.module.exports.cli.generateDocs
...
```
This can be reproduced by cloning [SinusBot/scripting-docs](https://github.com/SinusBot/scripting-docs), installing `tsd-jsdoc@2.0.0-beta.5` and running the command provided above.

Almost forgot: you also have to change the `template` path in the `config.json` as mentioned at the beginning...

**Comment by englercj** [comment]
Thanks for the bug report, I'll look into it as soon as I can.

**Comment by irgendwr** [comment]
@englercj Can you release a new version to make this usable?

**Comment by englercj** [comment]
I will try to remember to do so when I get home tonight.
