### ISSUE TITLE
VSCode debug configuration

### ISSUE THREAD

**Issue by bampakoa** [englercj/tsd-jsdoc#46]
Has anyone tried to debug with VSCode? I have setup a debug configuration through `launch.json` but it seems that `jsdoc` does not understand the `--inspect-brk` switch that is added from VSCode debuger.

> D:\Dev\tsd-jsdoc/node_modules/.bin/jsdoc.cmd -t --inspect-brk=27568 dist\Emitter.js -r . 
> The command-line option "t" requires a value.

**Comment by englercj** [comment]
Well that cmd line isn't correct. It should probably be `jsdoc.cmd --inspect-brk -t dist/publish.js -r`. Notice how the `-t` param is not next to the script name and the script it launches is `publish.js`.

**Comment by bampakoa** [comment]
For anyone having the same issue, `--inspect-brk` is added from VSCode by default. You can define a custom port for the debugger using the option `port` and then `--inspect-brk` will not be added and the solution suggested by @englercj  can easily be implemented.
