### ISSUE TITLE
Dot notation property?

### ISSUE THREAD

**Issue by charlesbodman** [englercj/tsd-jsdoc#47]
Issue coming from 
https://github.com/photonstorm/phaser/issues/3869

It looks like the tsd-jsdoc isn't handling dot notation properties. 

Is this something in the works, or should we adjust the jsdocs to conform? 

**Example**
GameConfig.js from Phaser 

https://github.com/photonstorm/phaser/blob/master/src/boot/Config.js#L61

```javascript
 * @property {*} [input.mouse.target=null] - [description]
 * @property {boolean} [input.touch=true] - [description]
 * @property {integer} [input.activePointers=1] - [description]
 * @property {*} [input.touch.target=null] - [description]
```

**Output**

https://github.com/photonstorm/phaser3-docs/blob/master/typescript/phaser.d.ts  (Line 306)

```javascript
    /**
     * [description]
     */
    "input.keyboard.target"?: any;
    /**
     * [description]
     */
    "input.mouse"?: boolean | object;
    /**
     * [description]
     */
    "input.mouse.target"?: any;
    /**
     * [description]
     */
    "input.touch"?: boolean;
    /**
     * [description]
     */
    "input.activePointers"?: integer;
    /**
     * [description]
     */
    "input.touch.target"?: any;
```

**Comment by englercj** [comment]
Are you sure this is an issue with tsd-jsdoc? As in, does this generate the expected jsdoc output?

I have a test of a typedef that include dot-notation for properties, and it works. What errors do you get when running tsd-jsdoc?

**Comment by charlesbodman** [comment]
I'm not sure if it is an issue with tsd-jsdoc. 
I just assumed that phaser is using tsd-jsdoc, but I'll do more testing to see if I can find the issue. 

Iv updated my question above with line numbers.

**Comment by englercj** [comment]
Can you create a minimal test case that reproduces this? Something I  can use in my test scripts rather than the entire phaser lib?

**Comment by charlesbodman** [comment]
Yeah, I'll try to reproduce with a simple example.

**Side note.** 
Looks like the solution has been solved by using separate typedefs.  
https://github.com/photonstorm/phaser/pull/3916

**Comment by englercj** [comment]
I've tested this in the new v2 release and it seems to be working as expected. If you encounter another issue, let me know.
