### ISSUE TITLE
Problem on windows

### ISSUE THREAD

**Issue by Munter** [englercj/tsd-jsdoc#48]
It seems that somewhere in either this reporter or jsdoc itself some path doesn't get resolved correctly on windows. The mix of forward and backwards slashes usually indicate a compatibility problem

```
PS C:\Users\pbm\git\assetgraph> jsdoc -t node_modules/tsd-jsdoc -r lib
FATAL: Unable to load template: Cannot find module 'C:\Users\pbm\git\assetgraph\node_modules\tsd-jsdoc/publish'
```

**Comment by englercj** [comment]
I'm currently doing a rewrite to remove dts-dom, and will include a fix for this when I get there.

**Comment by englercj** [comment]
v2 is out now, and I decided to keep the files in `dist`. I've updated the README to reflect where to point to.
