### ISSUE TITLE
Support for @enum block tag

### ISSUE THREAD

**Issue by bampakoa** [englercj/tsd-jsdoc#49]
I have noticed that `enum` block tag is not recognised by the library. How would one document an object such as the following?

```
var Intersect = {
    OUTSIDE: -1,
    INTERSECTING: 0,
    INSIDE: 1
};
```

**Comment by bampakoa** [comment]
You are right @englercj . That is strange because last time I checked it, I got a message `Unknown kind enum` :thinking:

**Comment by bampakoa** [comment]
@englercj Can I use it in conjunction with `exports` block tag since I need to reference it as an AMD module in another file?

**Comment by englercj** [comment]
Different files don't matter, and I'm not sure where you got the error `Unknown kind enum` from.

That being said, you didn't tell jsdoc that `Intersect` is an enum. You defined it as an object with some constant numbers inside it. Then, you use it like an enum in the other place. You say you return an `Intersect` object, but actually return a number.

Here is an example of how to format jsdoc for an enum: https://github.com/englercj/tsd-jsdoc/blob/a042e309e9a87135309306f4b6fde97da0ec256b/test/fixtures/enum_all.js

**Comment by bampakoa** [comment]
Thanks for the explanation @englercj . I was suspicious about the use of `Intersect` in the second file, that it actually returns a `Number` :smiley:
