### ISSUE TITLE
support for including original comments in d.ts file?

### ISSUE THREAD

**Issue by rich-earth** [englercj/tsd-jsdoc#56]
I'm not seeing original jsdoc comments included generated d.ts files, would this be hard to implement? 

Thanks
Rich

**Comment by englercj** [comment]
From the v2 changelog:

> JSDoc comments are not currently included in the output (public TS compiler API needed)

I haven't seen how I can make the TS compiler output comments yet. If you know which compiler APIs to use, please let me know. The API is fairly new and completely undocumented, so I haven't found everything yet.

**Comment by rich-earth** [comment]
Thanks. I haven't gone looking too deep but tested [this](https://github.com/otris/jsdoc-tsd) project which does manage to include the comments, but the defs generated are not as good. 

Appears to use [dts-dom](https://www.npmjs.com/package/dts-dom) to create the definitions instead of typescript package,  don't know if that would be of use?

**Comment by englercj** [comment]
v1 of this project used dts-dom. v2 uses the typescript compiler directly.

I need to find an API in the typescript compiler that allows me to build comment nodes in the AST.
