### ISSUE TITLE
Issues in generated files

### ISSUE THREAD

**Issue by no-more** [englercj/tsd-jsdoc#6]
Hi,

I'm just a user of forerunnerdb and they are using your tool to generate their types.d.ts file
I have pointed out a few issues on the generated file.
- types are generated inside of a class declaration
  - https://github.com/Irrelon/ForerunnerDB/issues/152
- Array are defined without type, should be typed <any> by default ?
  - https://github.com/Irrelon/ForerunnerDB/issues/154

The generated file is here : https://github.com/Irrelon/ForerunnerDB/blob/master/typescript/types.d.ts

I would like to check with you if this is a bug in this tool, or maybe it's possible to improve their jsdoc in order to fix those generation issues.

Thanks for your help.

**Comment by englercj** [comment]
Can you point me to the source that generates the bad TS? usually if there is no generic arg to the Array class, it is because there was no type specification in the source jsdoc.

**Comment by no-more** [comment]
Hi,

This is the input file (I think) : https://raw.githubusercontent.com/Irrelon/ForerunnerDB/master/js/dist/fdb-all.js
the online doc is here : https://www.forerunnerdb.com/source/doc/index.html
As you've said Array are untyped. I don't know much about jsdoc, what should the doc specify in order to return any[] in the typescript definition file ? Is it "Array.any" ?
Is it possible to automatically change "Array" to any[] when no type is specified ? tslint complains about Array without type.

Thanks.

**Comment by englercj** [comment]
Yeah we can assume `any[]` for untyped `Array`'s. The idea behind not doing that would be that the TS errors you got would make you go back and type your arrays properly in the docs. Because generally invalid TS output means invalid jsdoc.

**Comment by englercj** [comment]
As for the other one (types inside of class declarations) that is definitely a bug here. According to [this](https://github.com/Microsoft/TypeScript/issues/7061#issuecomment-183517330) what I need to do is queue up these types and add them to a namespace of the same name as the class.

Thanks for bringing this up!

**Comment by aendrew** [comment]
@englercj Confirming that approach solves the issue — I moved the types generated inside classes into a namespace of the same name as the class and it seems to make everything work, at least in terms of how [`github-api`](https://github.com/michael/github/pull/386) uses JSDoc. Happy to PR it, though be forewarned I am very new to the JSDoc plugin API!

**Comment by englercj** [comment]
Np, I'm working on v2 now. It adds some TS 2 features, uses a better emitter, and fixes a lot of these types of bugs.

I should have it done over the next week or two.

**Comment by jmls** [comment]
I take it v2 is not yet released ? ;)

**Comment by englercj** [comment]
Nope, haven't had time to come back to this; been extremely busy at work.

**Comment by englercj** [comment]
Getting closer on this, just a few more things to work out and I should be able to release v2 soon. Sorry its been so long :(

**Comment by englercj** [comment]
Got the module declaration stuff working for inner classes and types, as well as fixing array/object definitions.

I'll put out a v2 beta build shortly.
