### ISSUE TITLE
"declare module" may need quotes

### ISSUE THREAD

**Issue by Jaid** [englercj/tsd-jsdoc#61]
Thank you for all the work put into that great project, @englercj!
I currently develop [`jsdoc-tsd-webpack-plugin`](https://github.com/Jaid/jsdoc-tsd-webpack-plugin) which generates `tsd-jsdoc` output and [`better-docs`](https://github.com/SoftwareBrothers/better-docs) output through Webpack compilation.

[`array-to-object-keys`](https://github.com/Jaid/array-to-object-keys) is an example project from me. This is the important part:

```js
/** @module array-to-object-keys */
// Removed for simplicity
/**
 * Converts an array to an object with static keys and customizable values
 * @example
 * arrayToObjectKeys(["a", "b"])
 * // {a: null, b: null}
 * @example
 * arrayToObjectKeys(["a", "b"], "value")
 * // {a: "value", b: "value"}
 * @example
 * arrayToObjectKeys(["a", "b"], (key, index) => `value for ${key} #${index + 1}`)
 * // {a: "value for a #1", b: "value for b #2"}
 * @param {string[]} array Keys for the generated object
 * @param {valueGenerator|*} [valueGenerator=null] Optional function that sets the object values based on key and index
 * @returns {Object<string, *>} A generated object based on the array input
 */
export default (array, valueGenerator = null) => {
// Removed for simplicity
}
```

`tsd-jsdoc` generates:
```ts
/** @module array-to-object-keys
 */
declare module array-to-object-keys {
    /**
     * Converts an array to an object with static keys and customizable values
     * @example
     * arrayToObjectKeys(["a", "b"])
     * // {a: null, b: null}
     * @example
     * arrayToObjectKeys(["a", "b"], "value")
     * // {a: "value", b: "value"}
     * @example
     * arrayToObjectKeys(["a", "b"], (key, index) => `value for ${key} #${index + 1}`)
     * // {a: "value for a #1", b: "value for b #2"}
     * @param {string[]} array Keys for the generated object
     * @param {valueGenerator|*} [valueGenerator=null] Optional function that sets the object values based on key and index
     * @returns {Object<string, *>} A generated object based on the array input
     */
    function default(array: string[], valueGenerator?: valueGenerator | any): {
        [key: string]: any;
    };
}
```

This looks fine, but the syntax highlighting in my VSCode looked suspicious.

![image](https://user-images.githubusercontent.com/6216144/52082236-8ea7d380-259c-11e9-836a-6d2347a9f36d.png)

The module name is not parsed correctly with those dashes. Semi-official sources like [this one](https://definitelytyped.org/guides/best-practices.html) told me that module names need to be quoted.

Okay, I can fix this as long as JSDoc doesn't mind!

```diff
- /** @module array-to-object-keys */
+ /** @module "array-to-object-keys" */
```

It worked, the TSD output looks legit now, but... what is this abomination?

![image](https://user-images.githubusercontent.com/6216144/52082722-d9761b00-259d-11e9-81ac-bfc65500bde3.png)

The underscores in the file name were one of many impacts that told me that the `@module` annotation is the wrong place to hack in a fix for that.

So what do you recommend? Is this a case that should be included in `tsd-jsoc`?

Like:

```js
moduleName = moduleName.includes("-") ? `"${moduleName}"` : moduleName
```

Or did I understand something wrong on my side?

**Comment by englercj** [comment]
I would probably be fine for us to just always quote module names. Right now it uses `createIdentifier`, but not all module names are valid identifiers so that should be updated.

Thanks for the bug report.

**Comment by Jaid** [comment]
Yeah, I only included the filename screenshot to show that I can't just quote the identifier in `/** @module */`, because manually quoting the module has side effects on other JSDoc features like HTML filename generation.

Are you currently available and motivated for this task? If not, that's fine, I'll try to come up with a pull request then to do my part. I'm not very affiliated with TypeScript though.

**Comment by englercj** [comment]
If you can do a PR that would be great, if not I will get around to it at some point but I only work on projects on the weekends :)

**Comment by Jaid** [comment]
I got it done! :)

**Comment by irgendwr** [comment]
> I would probably be fine for us to just always quote module names.

Why did you end up quoting only invalid identifiers?

For me VS code **only** recognizes quoted module names (doesn't matter if valid or not).

**Comment by englercj** [comment]
Turns out unquoted modules are actually just namespaces, so I need to quote them all. Will fix.

**Comment by englercj** [comment]
Hopefully that fixes it up, got some other work I want to do and will do a release at some point.

**Comment by irgendwr** [comment]
Thanks, looking forward to a release!  😃 

We can finally use this again after I found at that the reason nothing worked was our use of `@mixin`.

**Comment by irgendwr** [comment]
Hi @englercj, would it be possible to release a new version soon-isch?
I don't like pushing stuff but I've got a pull-request that depends on the last commit.

Thanks and have a great day 😃

**Comment by englercj** [comment]
I had some water damage in my office that has prevented me from accessing my machine, and it has made me forget to do this. I will try to get on it from my chromebook sometime this weekend. Sorry!
