### ISSUE TITLE
Can @file be ignored?

### ISSUE THREAD

**Issue by arizonatribe** [englercj/tsd-jsdoc#68]
Hi again,
I was wondering if I could submit a PR to have `tsd-jsdoc` ignore `@file` JSDoc annotations? Of course there's nothing that those annotations should translate to in a Typescript definition, but I was hoping they could just be ignored.

Currently I have a lot of files that have JSDoc annotations like these at the top of the file:
```javascript
/**
 * @file Resolves the paths to folders and/or files which is needed by the build script.
 * @requires NODE:url#parse
 * @requires NODE:fs#existsSync
 * @requires NPM:fs-extra#moveFileSync
 * @requires ./paths.js
 * @requires ./flags.js
 */
```

I use those in a different JSDoc template (although they are of very _minor_ importance) and I'd prefer to keep them in there if I can. Right now it's throwing an error and I'm hoping it can just be modified similar to [how you're ignoring @event](https://github.com/englercj/tsd-jsdoc/blob/master/src/Emitter.ts#L283), then it wouldn't throw an error when building the definition.

I think all I'd need is to add something like this to the `src/Emitter.ts` to the `_parseTreeNode()` method [[1](https://github.com/arizonatribe/tsd-jsdoc/blob/fix/Files-and-Callbacks/src/typings/jsdoc.d.ts#L105)]. This worked for me locally when I modified the `node_modules/tsd-jsdoc/dist/Emitter.js` so I think it'll do the trick:
```javascript
            case 'file'
                return null;
```

Thanks again!

**Comment by englercj** [comment]
Yeah it should be ignored, it is not currently only because I didn't think to add it in.

**Comment by arizonatribe** [comment]
Okay cool. I'm adding that into this PR #69

Thanks again
