### ISSUE TITLE
Can the next version of this package be published to NPM?

### ISSUE THREAD

**Issue by arizonatribe** [englercj/tsd-jsdoc#75]
Would it be possible to get a new version of `tsd-jsdoc` published? Several of the changes/fixes that have been committed to the codebase since v2.1.3 was published to NPM would be really useful to have available to us.

Thanks!

**Comment by englercj** [comment]
Was waiting to see if we could resolve #73 and #74 first.

**Comment by englercj** [comment]
Also now #76 is open and I'd like to get that in too.

**Comment by arizonatribe** [comment]
Okay, just I've been waiting over a month for that patch to get published, and more stuff - completely unrelated in issue - seems to keep delaying it.

**Comment by englercj** [comment]
If your need is urgent you can always use a git dependency. No need to wait for a publish if you need something.

**Comment by arizonatribe** [comment]
Sure, I suppose, but one of the main advantages [semantic versioning](https://semver.org/) is not having to bundle dozens of little patches into one (infrequent) large release. You can save large releases for major changes and continue to publish small patches or minor (non-breaking) feature additions more frequently.

**Comment by englercj** [comment]
v2.2.0 has been published.
