### ISSUE TITLE
Has plan for supporting ES Module?

### ISSUE THREAD

**Issue by imcuttle** [englercj/tsd-jsdoc#78]
Hi, tsd-jsdoc is cool!
It throws `[TSD-JSDoc] Failed to find parent of doclet 'module.exports' using memberof 'module', this is likely due to invalid JSDoc.` when I use ES Module like `export default`.

**Comment by englercj** [comment]
Yeah this is an issue with jsdoc's parsing of ES6 modules. It doesn't do great job of it. The workarounds are to use named exports or to name your thing and export it as default later:

```js
/**
 * @class
 */
class MyThing {}

export default MyThing;
```
