### ISSUE TITLE
Consider using prettier?

### ISSUE THREAD

**Issue by Graham42** [englercj/tsd-jsdoc#84]
Using an autoformatter would save you time and effort in reviewing PRs, because wouldn't have to worry about manual code style review. [Prettier](https://prettier.io/) is an awesome autoformatter that I highly recommend. 

If you'd be open to this, I can open a PR.

**Comment by englercj** [comment]
I've never gotten an auto formatter to actually represent the style I want. It usually just gets close. I also don't spend much time on style comments in PRs anyway so you'll probably spend longer enabling this than I do commenting on PRs.

That being said I don't have strong feelings about this at all, if you want to give it a shot its all you. But I probably won't merge it if it changes the existing code in any significant way.

**Comment by Graham42** [comment]
I've done it for several of my own projects so don't mind taking a stab at it. 

I can see that it might not format somethings exactly the way someone prefers. For me, I've been using this for over a year now and the peace of mind of not having to worry about formatting ever again makes up for any preference of mine. I've come to not care how code is formatted so much, as long as it's autoformatted.
